import json
import sys
import os
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent
DIARY_DIR = PROJECT_ROOT / ".claude" / "diary"
DIARY_DIR.mkdir(parents=True, exist_ok=True)


def read_transcript():
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            return []
        lines = [l for l in raw.strip().splitlines() if l.strip()]
        records = []
        for line in lines:
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return records
    except Exception:
        return []


def extract_user_messages(records):
    messages = []
    for r in records:
        role = r.get("role") or (r.get("message") or {}).get("role")
        content = r.get("content") or (r.get("message") or {}).get("content")
        if role == "user" and content:
            if isinstance(content, str):
                messages.append(content[:500])
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        messages.append(block.get("text", "")[:500])
    return messages


def extract_files_modified(records):
    files = set()
    for r in records:
        raw = json.dumps(r)
        import re

        for m in re.finditer(r'"filePath":"([^"]+)"', raw):
            files.add(m.group(1))
    return sorted(files)


def extract_tool_counts(records):
    counts = {}
    for r in records:
        content = (
            (r.get("message") or {}).get("content") or r.get("content") or []
        )
        if isinstance(content, list):
            for block in content:
                if isinstance(block, dict) and block.get("type") == "tool_use":
                    name = block.get("name", "unknown")
                    counts[name] = counts.get(name, 0) + 1
    return counts


def next_diary_path():
    today = datetime.now().strftime("%Y-%m-%d")
    n = 1
    while True:
        p = DIARY_DIR / f"{today}-session-{n}.md"
        if not p.exists():
            return p
        n += 1


def write_diary(records):
    user_msgs = extract_user_messages(records)
    files = extract_files_modified(records)
    tools = extract_tool_counts(records)
    now = datetime.now()

    summary = (
        user_msgs[0][:200] if user_msgs else "(no user messages captured)"
    )
    task_count = len(user_msgs)

    tool_lines = (
        "\n".join(f"  - {k}: {v}" for k, v in sorted(tools.items()))
        or "  (none captured)"
    )
    file_lines = "\n".join(f"  - {f}" for f in files) or "  (none captured)"

    branch = "(unknown)"
    try:
        import subprocess

        result = subprocess.run(
            ["git", "-C", str(PROJECT_ROOT), "branch", "--show-current"],
            capture_output=True,
            text=True,
            timeout=3,
        )
        if result.returncode == 0:
            branch = result.stdout.strip() or "(detached)"
    except Exception:
        pass

    entry = f"""# Session Diary Entry (auto — pre-compact)

**Date**: {now.strftime('%Y-%m-%d')}
**Time**: {now.strftime('%H:%M')}
**Trigger**: PreCompact hook (context about to be compacted)
**Project**: {PROJECT_ROOT}
**Git Branch**: {branch}

## Task Summary
[Auto-captured — {task_count} user message(s) in session. First: "{summary}"]

## Work Summary
[Captured by hook — review conversation context for full details]

## Design Decisions Made
[Review conversation context]

## Actions Taken
- Files modified:
{file_lines}
- Tools used:
{tool_lines}

## Code Review & PR Feedback
[Review conversation context]

## Challenges Encountered
[Review conversation context]

## Solutions Applied
[Review conversation context]

## User Preferences Observed
[Review conversation context]

## Notes
Auto-generated by pre-compact hook. Run `/diary` in next session to review and enrich this entry.
"""

    path = next_diary_path()
    path.write_text(entry)
    return path


def main():
    records = read_transcript()
    path = write_diary(records)
    print(json.dumps({"diary_saved": str(path)}))


if __name__ == "__main__":
    main()
